project:
  name: "Resumic"
  state: "alpha"
  image: "https://github.com/resumic/schema/blob/master/media/logo.svg"
  website: "https://resumic.org"
  oneLiner: "Standardized and generic data schema for your resume/CV"
  description: |
    Easily share your machine readable data or export your resume/CV to a great looking website or PDF.
  version: "v0.1.0"

vision:
  type: "community"
  overview: |
    With resumic the goal is to enable everyone to have an up to date and awesome resume/CV.
  items:
    - "Generic schema additions only"
  concept: "Resumic strives to provide a standardized and generic data schema for resumes/CVs."
  aim: "Resumic aims to be a generic data schema with a thin layer of tooling around to enable easily working with your data."

supportLinks:
  documentation: "/docs"

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/resumic/schema/labels/starter%20issue" # replace dear-github with your actual url

emails:
  commercialSupport: "support@okkur.org"
  security: "security@okkur.org"
  coc: "coc@okkur.org"

copyright:
  year: "2017"

cla:
  copyrightHolder: "nzt.ventures GmbH"
  mail: "legal@nzt.ventures"

maintainers:
  - name: "Michael Grosser"
    nick: "stp-ip"
  - name: "Arman Mazdaee"
    nick: "armanmazdaee"

repo:
  link: "https://s.resumic.org/code"
  type: "Github"

issueTemplate:
  questions:
  - "OS"
  - "CLI version"

badges:
  - image: "https://img.shields.io/badge/state-alpha-blue.svg"
    alt: "state"
  - image: "https://img.shields.io/github/release/resumic/schema.svg"
    link: "https://github.com/resumic/schema/releases"
    alt: "release"
  - image: "https://img.shields.io/github/license/resumic/schema.svg"
    link: "LICENSE"
    alt: "license"
  - image: "https://travis-ci.org/resumic/schema.svg?branch=master"
    alt: "Build Status"
    link: "https://travis-ci.org/resumic/schema"

reposeed:
  configVersion: "v1"